# Dependabot config.
# Keep NPM and Composer packages up-to-date.

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    # Add reviewers
    reviewers:
      - 'Automattic/newspack-product'

  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `assets/components` directory
    directory: '/assets/components'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    # Add reviewers
    reviewers:
      - 'Automattic/newspack-product'

  # Enable version updates for Composer
  - package-ecosystem: 'composer'
    # Look for a `composer.lock` in the `root` directory
    directory: '/'
    # Check for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    # Add reviewers
    reviewers:
      - 'Automattic/newspack-product'
