export interface ActionCardProps {
	id?: string | number;
	title?: string | React.ReactNode;
	titleLink?: string;
	href?: string;
	description?: string | React.ReactNode;
	actionText?: React.ReactNode | string | null;
	badge?: string;
	className?: string;
	indent?: string;
	notification?: string | Error | null;
	notificationLevel?: 'error' | 'warning' | 'info';
	isMedium?: boolean;
	disabled?: boolean | string;
	hasGreyHeader?: boolean;
	toggleChecked?: boolean;
	toggleOnChange?: ( a: boolean ) => void;
	actionContent?: boolean | React.ReactNode | null;
	error?: Error | string | null;
	handoff?: string | null;
	isErrorStatus?: boolean;
	checkbox?: 'checked' | 'unchecked';
	isChecked?: boolean;
	children?: boolean | React.ReactNode;
	isSmall?: boolean;
	editLink?: string;
	simple?: boolean;
	secondaryActionText?: string;
	onSecondaryActionClick?: () => void;
	secondaryDestructive?: boolean;
	hasWhiteHeader?: boolean;
	noBorder?: boolean;
	noMargin?: boolean;
	collapse?: boolean;
	expandable?: boolean;
	draggable?: boolean;
	dragIndex?: number;
	onDragCallback?: ( index: number ) => void;
	dragWrapperRef?: React.MutableRefObject< HTMLDivElement | null >;
}
