name: PHP

on:
  pull_request:
  push:
    branches:
      - trunk
      - release
      - alpha
      - 'hotfix/**'
      - 'epic/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-php:
    uses: Automattic/newspack-scripts/.github/workflows/reusable-lint-php.yml@trunk

  test-php:
    uses: Automattic/newspack-scripts/.github/workflows/reusable-test-php.yml@trunk
