name: Release

on:
  push:
    branches:
      - release
      - alpha
      - 'hotfix/**'
      - 'epic/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: Automattic/newspack-scripts/.github/workflows/reusable-build.yml@refactor/deprecate-circle-ci

  release:
    needs: build
    uses: Automattic/newspack-scripts/.github/workflows/reusable-release.yml@1b654fae0446656ac8221ae7400a42bbd80b2140
    secrets:
      GITHUB_REPOSITORY: ${{ github.repository }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  post-release:
    if: github.ref == 'refs/heads/release'
    needs: release
    uses: Automattic/newspack-scripts/.github/workflows/reusable-post-release.yml@refactor/deprecate-circle-ci
